In [2]:
import pandas as pd
import numpy as np

In [90]:
messages=pd.read_csv('SMSSpamCollection',sep="\t",names=["labels","message"])

In [91]:
messages

labels                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Data Cleaning and Preprocessing

# Length Of message

In [92]:
messages['Length']=messages['message'].apply(len)

In [93]:
messages

labels                                            message  Length
0       ham  Go until jurong point, crazy.. Available only ...     111
1       ham                      Ok lar... Joking wif u oni...      29
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3       ham  U dun say so early hor... U c already then say...      49
4       ham  Nah I don't think he goes to usf, he lives aro...      61
...     ...                                                ...     ...
5567   spam  This is the 2nd time we have tried 2 contact u...     160
5568    ham               Will ü b going to esplanade fr home?      36
5569    ham  Pity, * was in mood for that. So...any other s...      57
5570    ham  The guy did some bitching but I acted like i'd...     125
5571    ham                         Rofl. Its true to its name      26

[5572 rows x 3 columns]

# Punctuation

In [94]:
import string 
punc=string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

Removing Punctuation From Mesaage

In [95]:
def remove_punctuation(data):
    s=[i for i in data if(i not in punc)]
    s="".join(s)
    return s

In [96]:
messages["New Message"]=messages['message'].apply(remove_punctuation)

In [97]:
messages

labels                                            message  Length  \
0       ham  Go until jurong point, crazy.. Available only ...     111   
1       ham                      Ok lar... Joking wif u oni...      29   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     155   
3       ham  U dun say so early hor... U c already then say...      49   
4       ham  Nah I don't think he goes to usf, he lives aro...      61   
...     ...                                                ...     ...   
5567   spam  This is the 2nd time we have tried 2 contact u...     160   
5568    ham               Will ü b going to esplanade fr home?      36   
5569    ham  Pity, * was in mood for that. So...any other s...      57   
5570    ham  The guy did some bitching but I acted like i'd...     125   
5571    ham                         Rofl. Its true to its name      26   

                                            New Message  
0     Go until jurong point crazy Available only in ...  
1                               Ok lar Joking wif u oni  
2     Free entry in 2 a wkly comp to win FA Cup fina...  
3           U dun say so early hor U c already then say  
4     Nah I dont think he goes to usf he lives aroun...  
...                                                 ...  
5567  This is the 2nd time we have tried 2 contact u...  
5568                Will ü b going to esplanade fr home  
5569  Pity  was in mood for that Soany other suggest...  
5570  The guy did some bitching but I acted like id ...  
5571                          Rofl Its true to its name  

[5572 rows x 4 columns]

# Remove Stopwords

In [98]:
from nltk.corpus import stopwords

In [99]:
sw=stopwords.words("english")
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [100]:
import os
def remove_stopwords(data):
    q=[w for w in data.split() if w.lower() not in sw]
    q=" ".join(q)
    return q

In [101]:
messages["Messages without Stop_words"]=messages["New Message"].apply(remove_stopwords)

In [102]:
messages

labels                                            message  Length  \
0       ham  Go until jurong point, crazy.. Available only ...     111   
1       ham                      Ok lar... Joking wif u oni...      29   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     155   
3       ham  U dun say so early hor... U c already then say...      49   
4       ham  Nah I don't think he goes to usf, he lives aro...      61   
...     ...                                                ...     ...   
5567   spam  This is the 2nd time we have tried 2 contact u...     160   
5568    ham               Will ü b going to esplanade fr home?      36   
5569    ham  Pity, * was in mood for that. So...any other s...      57   
5570    ham  The guy did some bitching but I acted like i'd...     125   
5571    ham                         Rofl. Its true to its name      26   

                                            New Message  \
0     Go until jurong point crazy Available only in ...   
1                               Ok lar Joking wif u oni   
2     Free entry in 2 a wkly comp to win FA Cup fina...   
3           U dun say so early hor U c already then say   
4     Nah I dont think he goes to usf he lives aroun...   
...                                                 ...   
5567  This is the 2nd time we have tried 2 contact u...   
5568                Will ü b going to esplanade fr home   
5569  Pity  was in mood for that Soany other suggest...   
5570  The guy did some bitching but I acted like id ...   
5571                          Rofl Its true to its name   

                            Messages without Stop_words  
0     Go jurong point crazy Available bugis n great ...  
1                               Ok lar Joking wif u oni  
2     Free entry 2 wkly comp win FA Cup final tkts 2...  
3                   U dun say early hor U c already say  
4           Nah dont think goes usf lives around though  
...                                                 ...  
5567  2nd time tried 2 contact u U £750 Pound prize ...  
5568                        ü b going esplanade fr home  
5569                        Pity mood Soany suggestions  
5570  guy bitching acted like id interested buying s...  
5571                                     Rofl true name  

[5572 rows x 5 columns]

# Stemming

In [103]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [104]:
def stemming(data):
    pr_s=[ps.stem(word) for word in data.split() if not word in sw]
    pr_s=" ".join(pr_s)
    return pr_s

In [105]:
messages["Messages with Stemming"]=messages["Messages without Stop_words"].apply(stemming)

In [107]:
messages

labels                                            message  Length  \
0       ham  Go until jurong point, crazy.. Available only ...     111   
1       ham                      Ok lar... Joking wif u oni...      29   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     155   
3       ham  U dun say so early hor... U c already then say...      49   
4       ham  Nah I don't think he goes to usf, he lives aro...      61   
...     ...                                                ...     ...   
5567   spam  This is the 2nd time we have tried 2 contact u...     160   
5568    ham               Will ü b going to esplanade fr home?      36   
5569    ham  Pity, * was in mood for that. So...any other s...      57   
5570    ham  The guy did some bitching but I acted like i'd...     125   
5571    ham                         Rofl. Its true to its name      26   

                                            New Message  \
0     Go until jurong point crazy Available only in ...   
1                               Ok lar Joking wif u oni   
2     Free entry in 2 a wkly comp to win FA Cup fina...   
3           U dun say so early hor U c already then say   
4     Nah I dont think he goes to usf he lives aroun...   
...                                                 ...   
5567  This is the 2nd time we have tried 2 contact u...   
5568                Will ü b going to esplanade fr home   
5569  Pity  was in mood for that Soany other suggest...   
5570  The guy did some bitching but I acted like id ...   
5571                          Rofl Its true to its name   

                            Messages without Stop_words  \
0     Go jurong point crazy Available bugis n great ...   
1                               Ok lar Joking wif u oni   
2     Free entry 2 wkly comp win FA Cup final tkts 2...   
3                   U dun say early hor U c already say   
4           Nah dont think goes usf lives around though   
...                                                 ...   
5567  2nd time tried 2 contact u U £750 Pound prize ...   
5568                        ü b going esplanade fr home   
5569                        Pity mood Soany suggestions   
5570  guy bitching acted like id interested buying s...   
5571                                     Rofl true name   

                                 Messages with Stemming  
0     Go jurong point crazi avail bugi n great world...  
1                                 Ok lar joke wif u oni  
2     free entri 2 wkli comp win FA cup final tkt 21...  
3                   U dun say earli hor U c alreadi say  
4             nah dont think goe usf live around though  
...                                                 ...  
5567  2nd time tri 2 contact u U £750 pound prize 2 ...  
5568                            ü b go esplanad fr home  
5569                            piti mood soani suggest  
5570  guy bitch act like id interest buy someth els ...  
5571                                     rofl true name  

[5572 rows x 6 columns]

In [108]:
messages["message"]=messages["New Message"]

In [111]:
messages["message"]=messages["Messages without Stop_words"]

In [112]:
messages["message"]=messages["Messages with Stemming"]

In [115]:
del messages['New Message']

In [117]:
del messages['Messages without Stop_words']

In [118]:
del messages['Messages with Stemming']

In [119]:
messages

labels                                            message  Length
0       ham  Go jurong point crazi avail bugi n great world...     111
1       ham                              Ok lar joke wif u oni      29
2      spam  free entri 2 wkli comp win FA cup final tkt 21...     155
3       ham                U dun say earli hor U c alreadi say      49
4       ham          nah dont think goe usf live around though      61
...     ...                                                ...     ...
5567   spam  2nd time tri 2 contact u U £750 pound prize 2 ...     160
5568    ham                            ü b go esplanad fr home      36
5569    ham                            piti mood soani suggest      57
5570    ham  guy bitch act like id interest buy someth els ...     125
5571    ham                                     rofl true name      26

[5572 rows x 3 columns]

# Creating Bags of Words

In [125]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
X=cv.fit_transform(messages['message']).toarray()

In [126]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [128]:
X.shape

(5572, 5000)

In [131]:
y=pd.get_dummies(messages['labels'])
y=y.iloc[:,1].values

In [136]:
pd.Series(y)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Length: 5572, dtype: uint8

# Train Test Split

In [137]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.20)

In [139]:
X_train.shape

(4457, 5000)

In [140]:
X_test.shape

(1115, 5000)

In [141]:
y_train.shape

(4457,)

# Training Model using Naive Bias

In [142]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [143]:
y_pred=spam_detect_model.predict(X_test)

In [145]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [146]:
y_pred.shape

(1115,)

In [151]:
pd.DataFrame({'Predicted':y_pred,'Original':y_test})

Predicted  Original
0             0         0
1             1         1
2             0         0
3             0         0
4             0         0
...         ...       ...
1110          0         0
1111          0         0
1112          0         0
1113          1         1
1114          0         0

[1115 rows x 2 columns]

In [152]:
spam_detect_model.score(X_train,y_train)

0.9899035225487997

In [153]:
spam_detect_model.score(X_test,y_test)

0.9829596412556054

In [154]:
from sklearn.metrics import confusion_matrix
confusin_m=confusion_matrix(y_test,y_pred)

In [155]:
confusin_m

array([[943,  12],
       [  7, 153]], dtype=int64)